services:
  postgres:
    image: postgres:latest
    container_name: postgres-ielts
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ielts
      - POSTGRES_USER=postgres
    networks:
      - ielts-be
  
  redis:
    image: redis:latest
    container_name: redis-ielts
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=admin
    networks:
      - ielts-be

networks:
  ielts-be:
    driver: bridge

volumes:
  postgres-data:
  redis-data:

